Add .ssh folder to clonerefs image
pusher/testing pull request #27
Opened 2019-06-07 14:28 UTC by JoelSpeed

Make the `/home/prow/.ssh` folder ahead of time, it is required by the clonerefs process if using SSH to clone repositories

2019-06-07 14:30 UTC, wonderhoss requested changes

2019-06-07 14:30 UTC, gargath commented on images/clonerefs/Dockerfile
> +RUN mkdir -p /home/prow/.ssh
I don't know whether clonerefs cares, but normally you'd also then need to
```
chown -R prow:root /home/prow
```
and
```
chmod 0700 /home/prow/.ssh
```

2019-06-07 14:32 UTC, JoelSpeed commented
/retest

2019-06-07 15:15 UTC, JoelSpeed commented
/retest

2019-06-11 13:30 UTC, JoelSpeed commented
We decided this was no longer required

2019-06-11 13:30 UTC, closed without merging